### ISSUE TITLE
scrpy doesnt pop up

### ISSUE THREAD

**Issue by Flight-X** [sisco311/scrcpy-snap#14]
summary:   Display and control your Android device
publisher: sisco311
store-url: https://snapcraft.io/scrcpy
contact:   https://github.com/sisco311/scrcpy-snap/issues
license:   Apache-2.0
description: |
  This application provides display and control of Android devices connected on USB (or over
  TCP/IP). It does not require any root access.  It works on GNU/Linux, Windows and MacOS.
  
  This is an unofficial snap. The code of scrcpy can be found at:
  https://github.com/Genymobile/scrcpy
commands:
  - scrcpy.adb
  - scrcpy
snap-id:      M7yvgnqOvyQj64bolfpawIAEwHv7dQ5G
tracking:     latest/stable
refresh-date: today at 20:46 IST
channels:
  latest/stable:    v1.12               2020-03-26 (211) 85MB -
  latest/candidate: ^                                         
  latest/beta:      v1.12.1-10-g7bb9163 2020-03-27 (214) 85MB -
  latest/edge:      v1.12-1-g71df317    2019-12-10 (202) 81MB -
installed:          v1.12                          (211) `85MB` -
When i run the cmd scrcpy i got this and nothing appers on the screen
2020/04/14 22:55:21.816933 cmd_run.go:893: WARNING: cannot start document portal: write unix @->@/tmp/dbus-JrtrgGH41M: write: broken pipe
INFO: scrcpy 1.12 <https://github.com/Genymobile/scrcpy>
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed. 5.8 MB/s (26196 bytes in 0.004s)
No protocol specified
Segmentation fault
root@Flight-X:/home/stelph# java.io.FileNotFoundException: /data/system/theme_config/theme_compatibility.xml (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:231)
	at java.io.FileInputStream.<init>(FileInputStream.java:165)
	at java.io.FileInputStream.<init>(FileInputStream.java:112)
	at java.io.FileReader.<init>(FileReader.java:58)
	at miui.content.res.ThemeCompatibilityLoader.getVersion(ThemeCompatibilityLoader.java:108)
	at miui.content.res.ThemeCompatibilityLoader.getConfigDocumentTree(ThemeCompatibilityLoader.java:126)
	at miui.content.res.ThemeCompatibilityLoader.loadConfig(ThemeCompatibilityLoader.java:59)
	at miui.content.res.ThemeCompatibility.<clinit>(ThemeCompatibility.java:31)
	at miui.content.res.ThemeCompatibility.isThemeEnabled(ThemeCompatibility.java:111)
	at android.content.res.MiuiResourcesImpl.<clinit>(MiuiResourcesImpl.java:41)
	at android.content.res.Resources.<init>(Resources.java:267)
	at android.content.res.MiuiResources.<init>(MiuiResources.java:49)
	at android.content.res.Resources.getSystem(Resources.java:190)
	at android.app.LoadedApk.<init>(LoadedApk.java:211)
	at android.app.ContextImpl.createSystemContext(ContextImpl.java:2332)
	at android.app.ActivityThread.getSystemContext(ActivityThread.java:2199)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.Workarounds.fillAppInfo(Workarounds.java:66)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:56)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:34)
	at com.genymobile.scrcpy.Server.main(Server.java:163)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:388)

**Comment by sisco311** [comment]
Please try the latest version. Does it work?

**Comment by brlin-tw** [comment]
Closing due to inactivity, feel free to reopen this issue if the problem is still reproducible.
