### ISSUE TITLE
scrcpy 

### ISSUE THREAD

**Issue by usef-zineb1111** [sisco311/scrcpy-snap#22]
scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
/usr/local/share/scrcpy/scrcpy-server:...shed. 0.6 MB/s (22546 bytes in 0.035s)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalArgumentException: Expecting 6 parameters
	at com.genymobile.scrcpy.Server.createOptions(Server.java:71)
	at com.genymobile.scrcpy.Server.main(Server.java:132)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)

**Comment by sisco311** [comment]
Do you still have this issue with the latest version?

**Comment by brlin-tw** [comment]
Not reproducible in the current version, closing...
